# Generated by Django 5.2.7 on 2025-11-09 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voter',
            name='otp',
        ),
        migrations.AddField(
            model_name='voter',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voter',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='voter',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
