# Generated by Django 5.2.7 on 2025-11-09 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting_app', '0002_remove_voter_otp_voter_ip_address_voter_user_agent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
